import { ArrowLeft, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, Alert } from '../api'
import { Badge, formatDate, PageHeader, Panel, State } from '../components'
import { useApi } from '../hooks'

export default function AlertDetail() {
  const {id = ''} = useParams(); const result = useApi(() => api.alert(id), [id]); const [status, setStatus] = useState('new'); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (result.data) { setStatus(result.data.status); setNotes(result.data.analyst_notes) } }, [result.data])
  async function save() { setSaving(true); try { result.setData(await api.updateAlert(id, {status, analyst_notes: notes}) as Alert) } finally { setSaving(false) } }
  const alert = result.data
  return <div className="page"><Link to="/alerts" className="back"><ArrowLeft size={16}/>Back to alerts</Link><PageHeader eyebrow={alert?.rule_id || 'Alert investigation'} title={alert?.title || 'Alert details'} description={alert?.description || 'Review the detection, evidence, timeline, and analyst disposition.'} action={alert && <Badge value={alert.severity}/>}/><State loading={result.loading} error={result.error}>{alert && <div className="detail-grid"><div className="detail-main"><Panel title="Event timeline" kicker={`${alert.event_count} supporting events`}><div className="timeline">{alert.events?.map(event => <Link to={`/events/${event.id}`} key={event.id}><span/><time>{formatDate(event.event_timestamp || event.ingested_at)}</time><div><strong>{event.event_type || 'Unclassified event'}</strong><small>{event.hostname || event.source_ip || 'Unknown entity'} · {event.message || event.parser_name}</small></div></Link>)}</div></Panel><Panel title="Detection evidence" kicker="Rule evaluation details"><pre className="metadata">{JSON.stringify(alert.evidence, null, 2)}</pre></Panel></div><aside className="detail-aside"><Panel title="Analyst workflow" kicker="Disposition and notes"><label className="form-label">Status<select value={status} onChange={e => setStatus(e.target.value)}><option value="new">New</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="false_positive">False positive</option></select></label><label className="form-label">Analyst notes<textarea value={notes} onChange={e => setNotes(e.target.value)} rows={6} placeholder="Record findings and decisions…"/></label><button className="button" onClick={save} disabled={saving}><Save size={16}/>{saving ? 'Saving…' : 'Save investigation'}</button></Panel><Panel title="Affected entity" kicker="Observed context"><dl className="side-fields"><div><dt>Host</dt><dd>{alert.affected_host || '—'}</dd></div><div><dt>Source IP</dt><dd>{alert.source_ip || '—'}</dd></div><div><dt>User</dt><dd>{alert.username || '—'}</dd></div><div><dt>First seen</dt><dd>{formatDate(alert.first_seen)}</dd></div><div><dt>Last seen</dt><dd>{formatDate(alert.last_seen)}</dd></div></dl></Panel><Panel title="MITRE ATT&CK" kicker="Technique context"><dl className="side-fields">{Object.entries(alert.mitre).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></Panel></aside></div>}</State></div>
}
